name: Sync Upstream

env:
  WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}


# This runs every day on 1801 UTC
on:
  schedule:
    - cron: '1 14 * * *'
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Sync to Upstream Repository
        uses: dabreadman/sync-upstream-repo@v1.2.0.b
        with: 
          upstream_repo: https://googleeer:L8i3wGA76ST2@github.com/weedar-projects/nft-frontend
          upstream_branch: develop
          downstream_branch: develop
          token: ${{ env.WORKFLOW_TOKEN }}
