name: SYNC_NFT_DEV

on:
  workflow_dispatch:
  schedule: 
  - cron: "*/30 * * * *"
  
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Sync and merge upstream repository with your current repository
        uses: dabreadman/sync-upstream-repo@v1.2.0.b
        with:
          # URL of gitHub public upstream repo
          upstream_repo: https://github.com/weedar-projects/nft-frontend.git
          # Branch to merge from upstream (defaults to downstream branch)
          upstream_branch: develop
          # Branch to merge into downstream
          downstream_branch: develop
          # GitHub Bot token
          token: ${{ secrets.WEEDAR_DEVELOP }}

      
